### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AlexanderHolmes0** [AlexanderHolmes0/Sport_Sched_Viz#1]
- [x] Soft Constraints🫠
- [x] Hard Constraints (Needs Double Checking✅)
- [ ] Any Changes to the Viz are Welcomed (Plz Contribute to my Repo🙏)
- [x] Add AMPL Model and Data🐆
